### ISSUE TITLE
Role not published to Ansible Galaxy

### ISSUE THREAD

**Issue by benformosa** [linux-system-roles/crypto_policies#22]
Most of the other linux-system-roles roles are published to [Ansible Galaxy](https://galaxy.ansible.com/linux-system-roles), but not this one.
Or should I be using the [collection](https://galaxy.ansible.com/fedora/linux_system_roles)?

**Comment by richm** [comment]
> Most of the other linux-system-roles roles are published to [Ansible Galaxy](https://galaxy.ansible.com/linux-system-roles), but not this one.
> Or should I be using the [collection](https://galaxy.ansible.com/fedora/linux_system_roles)?

Yes, please use the collection.
